### ISSUE TITLE
Local resources

### ISSUE THREAD

**Issue by davidleach** [matthew6project/thirtyone#11]
This needs to be a way to manage basic contact information on people/businesses/organizations which can serve as a resource.  Examples might be people willing to provide automotive assistance, care groups, counseling resources, etc.

A user should be able to create a resource type and name it.  Then resources of that type can be created.  If a customer needs a certain type of resource, they can be printed/emailed for them.

**Comment by Clete2** [comment]
Category: Local resource category
Item: Local resource
Fields on item: Contact name, business name, phone, email, website, address
