### ISSUE TITLE
Validate Phone when creating Person

### ISSUE THREAD

**Issue by Clete2** [matthew6project/thirtyone#167]
- [ ] Client Side
- [ ] Server Side

### For client side
Utilize [inputmask](https://github.com/RobinHerbots/jquery.inputmask) for the phone field in the Create/Edit person form.

See [local_resources_form.js](https://github.com/matthew6project/thirtyone/blob/master/app/assets/javascripts/app.local_resources.js) for an example.

### For server side
Update the validations in the Person model. Look up how to use "validates_format_of" for help starting.
(You could use validates_numericality_of in conjunction with validates_length_of. Your choice.)

**Comment by jjulien** [comment]
@Clete2 , the link on this issue is a 404.

**Comment by Clete2** [comment]
@jjulien fixed the link. Thanks.

**Comment by tasmar** [comment]
Closed by merge #242
