### ISSUE TITLE
Deleting a Person Should Set to Inactive

### ISSUE THREAD

**Issue by jjulien** [matthew6project/thirtyone#171]
We don't want to actually delete any people from the database, we need to add an active field to the person model and flip this to inactive when a person is deleted.

- Create a migration that adds the `active` column to the Person model
- Set a default scope on the `Person` model that sets `where active = 't'` [Scope Documentation](http://guides.rubyonrails.org/active_record_querying.html#applying-a-default-scope)
- Check the site for any `delete` or `destroy` person code and refactor it to use the `active switch.

**Comment by davidleach** [comment]
Consider using this gem: https://github.com/rubysherpas/paranoia
