### ISSUE TITLE
Direct to User page after creating user from create person page

### ISSUE THREAD

**Issue by Clete2** [matthew6project/thirtyone#193]
When a new person is created and the radio button is selected for a user to be created, redirect the end user to the edit User page for the new user. From there, they can edit the user's role.

- When a user is created, they can have the default user permission
- When a user is being edited, show a link to the user's profile page from the edit person page
- Maybe also show a link to the user's profile page from the "show" person page.

Depends on #191.

**Comment by andela-ooranagwa** [comment]
Hi! I've submitted a `PR` to fix this issue. Could you checkout and give me feedback.
