### ISSUE TITLE
Ensure use of Strong Params

### ISSUE THREAD

**Issue by Clete2** [matthew6project/thirtyone#203]
We should use [strong parameters](http://edgeapi.rubyonrails.org/classes/ActionController/StrongParameters.html) whenever we are using params. Find the places where we are using 'params' and make sure we are using strong params (e.g. user_params, etc).

**Comment by andela-ooranagwa** [comment]
Hi! I've submitted a `PR` that should fix this. Could you review it and give me your feedback?

**Comment by andela-ooranagwa** [comment]
I noticed some of your controllers (household, people, local_resource, people, roles, work_schedule) could use some rewrite and improvement. I could help with plans on how to optimize them.

**Comment by davidleach** [comment]
@andela-ooranagwa Thank you so much for the PR!  We have our weekly meeting tonight so we will review and get back to you.  We've also been discussing a major refactoring of some of the controllers you mention so we'll see where we are on that and let you know.  We'd love the help!

**Comment by davidleach** [comment]
@andela-ooranagwa We currently have some significant work underway on both people and households.  What are your thoughts for improvements on the roles controller?

**Comment by andela-ooranagwa** [comment]
I like that the `role controller` is not too bulky and focuses more on just *CRUD* operations. The parts I'd vote for improvement will be the `create`, `update` and `bulk_assign_create` actions.

**Comment by andela-ooranagwa** [comment]
I think the `create` and `update` actions are affected by the nature of the `permission` attribute of `roles`. One way to solve it will be to modify the db relationship. Another will be to implement minor improvements and modifications in calculating the permissions. Like for the update we can have:

```ruby

def update
  aRPrm = params[:PermGrp]
  respond_to do |format|
    @role.permissions = aRPrm.inject(0){ |sum, num| sum + num.to_i }

    if @role.update(role_params)
      format.html { redirect_to @role, notice: 'Role was successfully updated.' }
      format.json { head :no_content }
    else
      format.html { render action: 'edit' }
      format.json { render json: @role.errors, status: :unprocessable_entity }
    end
  end
end

```

**Comment by andela-ooranagwa** [comment]
I'm curious; how do you then interpret a user's permission level, given that they are all summed together?

**Comment by jjulien** [comment]
@andela-ooranagwa we are using the binary representation of the `permissions` attribute to determine what permissions they have.  

Example:
```
PERM_RO_PERSON    = 0000 0000 0000 0001  # 1
PERM_RW_PERON     = 0000 0000 0000 0010  # 2 
PERM_RO_SCHEDULE  = 0000 0000 0000 0100  # 4
PERM_RW_SCHEDULE  = 0000 0000 0000 1000  # 8
```

If I have a role with a permission value of `3` then they have the `PERM_RO_PERSON` and `PERM_RW_PERSON` permission.  

In code we are usually just checking if they have a single permission, say `PERM_RW_PERSON` for the `people_controller#edit` method.  We do a binary AND operation to check if they have this permission bit set.  

Example:
```
role.permissions = 3
role.permissions & PERM_RW_PERSON # Returns 2
```

The binary AND will either return the permission bit we checked against or 0 if that bit is absent.

We do all these checks using the `has_access?` method on the user model
```
  def has_access?(permission)
    permissions & PERM_ADMIN > 0 || permissions & permission > 0
  end
```

The checks are invoked by the Pundit policy that correlates to each controller and method.  These are located in the `policies` folder.  

Here is the policy for the `people_controller#edit` method.
https://github.com/matthew6project/thirtyone/blob/master/app/policies/person_policy.rb#L25-L31

**Comment by andela-ooranagwa** [comment]
Oh, I see. That's cool :+1:

**Comment by jjulien** [comment]
@andela-ooranagwa We like your ideas for the `role_controller`.  This is the first Ruby on Rails project for the majority of us, which is why you've probably noticed some of the code is lacking a "ruby" feel.  

We like what you did with the strong params, so if you want to polish the `role_controller` as well, feel free.  

I'm going to close this issue as resolved, looking forward to your next PR.  

Thanks!
