### ISSUE TITLE
Format Local Resources Index Page

### ISSUE THREAD

**Issue by jjulien** [matthew6project/thirtyone#214]
The Local Resources index page needs some formatting work.

There should probably be an `<h1>Local Resources</h1>` title.  The button needs to be of `class="medium"`.  There should be some text on the page when there are no local resources saying, no local resources exist yet, click the button to create one, or something to that effect.  

When there are local resources the left margin of the button doesn't match the the left margin of the local resource box.

**Comment by mread1208** [comment]
Looks like you guys have done some work on this in the past 3 months.  I think we can mark this closed now.
