### ISSUE TITLE
Allow deleting a household

### ISSUE THREAD

**Issue by jjulien** [matthew6project/thirtyone#216]
When a household is deleted all of the members either need to be deleted or reassigned to another household.

We should never truly delete the household, just set it to inactive.  This issue is dependent on #171 which will enable deleting people.

**Comment by davidleach** [comment]
Inactivating the household will be pretty easy if we implement it like we did for people.  When it comes to reassignment, what should that look like?

Option: 

1. User tries to delete household
2. All members of household are listed with two actions, 'Delete' and 'Change Household'
3. Those marked as 'Delete' will be inactivated with the household
4. Each time 'Change Household' is clicked for a person the user will be presented the opportunity to search for and select a new household, (even allow them to create a new household for the person).
5. After all members have had an option selected for them the user chooses 'Delete Household' action which executes the selected option for each member.

With this option it feels like the selection/creation of a household for a person should look and act like it does when creating a new person.  Maybe we could leverage the same code/views??

Other suggestions for workflow?

**Comment by jjulien** [comment]
I think that sounds like a good flow and we can definitely re-use the views.  They are split into partials already so that should be pretty easy.

**Comment by Clete2** [comment]
I agree that this is a good flow. What happens when you delete a user and they are the last in the household? Does it deactivate household too?

**Comment by davidleach** [comment]
I think it should. We could use an Activerecord callback when a person is inactivated to check if the household is empty and inactivate if it is.
