### ISSUE TITLE
New Household Redirect

### ISSUE THREAD

**Issue by jjulien** [matthew6project/thirtyone#243]
When a new household is created from the `Household` page, the user is redirected to the `New Person` to create the first person (aka head of household).   When the save the new person they should be redirected back to the edit household page, so they can optionally add additional members.

This should function similar to how adding new members to an existing household works when editing a household.  The `redirect_to_url` parameter is used to tell the `PeopleController` that it needs to redirect to use to a page other than the show person page.

**Comment by mread1208** [comment]
Fixed this with Pull request #264
