### ISSUE TITLE
Password Field on Person Page

### ISSUE THREAD

**Issue by Clete2** [matthew6project/thirtyone#63]
A person should be able to change their password from the "My Account" / Person edit page. There should be 2 boxes (password and password confirm).

If a person is editing a person other than themselves, the password box should be grayed out. Unless the editing person is an admin, then they should be able to change the other person's password.

**Comment by davidleach** [comment]
Devise, which we use for authentication, allows for this.  See for examples: https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-password

**Comment by Clete2** [comment]
See #191.
