### ISSUE TITLE
Add notes to show person page

### ISSUE THREAD

**Issue by jjulien** [matthew6project/thirtyone#72]
Dependent on #71 
We need to add prayer requests, needs, and comments to the display of a person object.  We want to make sure we only display those notes for which the logged in user has a READ privilege to see.

**Comment by jjulien** [comment]
![img_1638](https://cloud.githubusercontent.com/assets/1606961/13369307/d3990b74-dcb8-11e5-9a74-6db0907b5279.JPG)

**Comment by jjulien** [comment]
![img_1638](https://cloud.githubusercontent.com/assets/1606961/13369371/9ef92aa6-dcb9-11e5-96b8-12f8cb979280.jpg)

**Comment by Clete2** [comment]
Already merged
